#!/bin/bash
# script to build thunderbirddata.tar.xz after an update
# must be run in /home/robert
tar --xz -C /home/robert --exclude=*/ImapMail -cvf thunderbirddatarpi.tar.xz .thunderbird .thunderbirdMail
