#!/bin/sh
##################################################
# thunderbirddatarpi:postinst
##################################################

# this script only runs during configure.
# if $1 is not equal to configure, exit
test "$1" = "configure" || exit 0;

# xz-utils is required for untarring
# apt install also does not work here

# /home/robert/thunderbirddatarpi.tar.xz must be extracted
# thunderbirddata.tar.xz  must not contain any emails including no local folders
# since these will overwrite existing emails during installation
cd /home/robert
sudo -u robert tar --overwrite --xz -xvf thunderbirddatarpi.tar.xz

# remove the file
rm -v /home/robert/thunderbirddatarpi.tar.xz
rm -v /home/robert/buildthdata
rm -v /home/robert/xtractthdata
